/*    ==Scripting Parameters==

    Source Server Version : Version120 (12.0.2000)
    Source Database Engine Edition : Enterprise
    Source Database Engine Type : Standalone

    Target Server Version : Version130
    Target Database Engine Edition : Enterprise
    Target Database Engine Type : Standalone
*/
USE [master]
GO
CREATE DATABASE [HostViz_IGT_Template]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HostViz_IGT_Template', FILENAME = N'C:\SQL_DB\HostViz_IGT_Template.mdf' , SIZE = 109568KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HostViz_IGT_Template_log', FILENAME = N'C:\SQL_DB\HostViz_IGT_Template_log.ldf' , SIZE = 15040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [HostViz_IGT_Template] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HostViz_IGT_Template].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HostViz_IGT_Template] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET ARITHABORT OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HostViz_IGT_Template] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HostViz_IGT_Template] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET  DISABLE_BROKER 
GO
ALTER DATABASE [HostViz_IGT_Template] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HostViz_IGT_Template] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [HostViz_IGT_Template] SET  MULTI_USER 
GO
ALTER DATABASE [HostViz_IGT_Template] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HostViz_IGT_Template] SET DB_CHAINING OFF 
GO
ALTER DATABASE [HostViz_IGT_Template] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [HostViz_IGT_Template] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [HostViz_IGT_Template] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'HostViz_IGT_Template', N'ON'
GO
ALTER DATABASE [HostViz_IGT_Template] SET  READ_WRITE 
GO
